<a href="https://colab.research.google.com/github/SergioQS/AI_and_ML/blob/main/CourseAI_Week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

In [3]:
#creando listas

listas1 = [1,5,8,10]
print("listas1 = ", listas1)
listas2 = [1,5,8,10, "intelligencia", False]
print("listas2 = ", listas2)
listas3 = [[2,3,5],[8,3,1],[2,7,20]]
print("listas3 = ", listas3)

listas1 =  [1, 5, 8, 10]
listas2 =  [1, 5, 8, 10, 'intelligencia', False]
listas3 =  [[2, 3, 5], [8, 3, 1], [2, 7, 20]]


In [7]:
#Creando arreglos desde listas

n = [2,3,214]
m = np.array(n)
print("tipo de dato: ", m.dtype)
print("forma del arreglo: ", m.shape)
print("tamaño del arreglo: ", m.size)
print("dimension del arreglo ", m.ndim)
print(m)


tipo de dato:  int64
forma del arreglo:  (3,)
tamaño del arreglo:  3
dimension del arreglo  1
[  2   3 214]


In [10]:
n = [123.121]
m = np.array(n)
print(m.dtype)

float64


In [11]:
n = [12,2,46]
m = np.array(n, dtype ="float16")
print("tipo de dato: ", m.dtype)
print("forma del arreglo: ", m.shape)
print("tamaño del arreglo: ", m.size)
print("dimension del arreglo ", m.ndim)
print(m)

tipo de dato:  float16
forma del arreglo:  (3,)
tamaño del arreglo:  3
dimension del arreglo  1
[12.  2. 46.]


In [13]:
a = np.array([[1,23,14,5],
              [4,34,324,21]])
a.shape = (4,2)                      # Redimensionar arrays
print("tipo de dato: ", a.dtype)
print("forma del arreglo: ", a.shape)
print("tamaño del arreglo: ", a.size)
print("dimension del arreglo ", a.ndim)
print(a)

tipo de dato:  int64
forma del arreglo:  (4, 2)
tamaño del arreglo:  8
dimension del arreglo  2
[[  1  23]
 [ 14   5]
 [  4  34]
 [324  21]]


In [44]:
 #Indexación y slicing

 a = np.array([[1,23,14,5],
               [4,34,324,21],
               [3,42],
               2,123,3], dtype = object)
 # se debe especificar dtype = object porque se está creando un array que contiene multiples listas de distinto tamaño y enteros
print(a)
print(a[0])
print(a[1][3])
print(a[0:2])
print(a[-1])

[list([1, 23, 14, 5]) list([4, 34, 324, 21]) list([3, 42]) 2 123 3]
[1, 23, 14, 5]
21
[list([1, 23, 14, 5]) list([4, 34, 324, 21])]
3


In [28]:
 a = np.arange(20)
 print(a)
 print(a[0:19:2])           # se imprimen los valores cada 2 elementos
 print(a[-8:-1])
 print(a[12:1:-2])          # se imprimen de adelante hacia atrás gracias al negativo (-2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  2  4  6  8 10 12 14 16 18]
[12 13 14 15 16 17 18]
[12 10  8  6  4  2]
[]


In [45]:
m = np.arange(20)
m[0:4] = [100,101,3,22223]            # se reemplazan los valores especificados en el array original
print(m)

[  100   101     3 22223     4     5     6     7     8     9    10    11
    12    13    14    15    16    17    18    19]
